---
- name: base64
  hosts: "{{ target_group }}"
  vars:
    my_var: "Hello"
    my_base64: "SGVsbG8="
  tasks:
    - name: base64 encode
      debug:
        msg: "Hello base64: {{ my_var | b64encode }}"

    - name: base64 decode
      debug:
        msg: "SGVsbG8= decode: {{ my_base64 | b64decode }}"